// utils/pdfTemplates/enquiryPdf.js
const path = require("path");
const fs = require("fs");

module.exports = (doc, data) => {
  const {
    _id,
    studentName,
    dob,
    gender,
    isFirstGraduate,
    studentEmail,
    studentMobile,

    fatherName,
    fatherEmail,
    fatherMobile,

    motherName,
    motherEmail,
    motherMobile,

    address = {},
    community,
    courseRequired = [],

    twelfthSchoolName,
    twelfthSchoolAddress,
    twelfthSchoolBoard,
    twelfthRegisterNo,

    tenthSchoolBoard,
    twelfthMarks = {},

    dateOfVisit,
    signature,
    status,
    createdAt,
    updatedAt,
  } = data;

  // ===== Header =====
  const logoPath = path.join(__dirname, "../../public/assets/logo.png");
  if (fs.existsSync(logoPath)) {
    doc.image(logoPath, 50, 40, { width: 80 });
  }

  doc.fillColor("#2c3e50").fontSize(22).text("SECE Admission Enquiry", 150, 50);
  doc.moveDown(2);

  // Helper for section headings
  const sectionHeading = (title) => {
    doc.fillColor("#3498db").fontSize(16).text(title, { underline: true });
    doc.moveDown(0.5);
  };

  // Helper for key-value pairs
  const infoRow = (label, value) => {
    doc.fillColor("#000").fontSize(12).text(`${label}: ${value || "-"}`);
  };

  // ===== Student Details =====
  sectionHeading("Student Details");
  infoRow("Enquiry ID", _id);
  infoRow("Name", studentName);
  infoRow("DOB", dob ? new Date(dob).toLocaleDateString() : "-");
  infoRow("Gender", gender);
  infoRow("First Graduate", isFirstGraduate ? "Yes" : "No");
  infoRow("Email", studentEmail);
  infoRow("Mobile", studentMobile);
  doc.moveDown();

  // ===== Father Details =====
  sectionHeading("Father Details");
  infoRow("Name", fatherName);
  infoRow("Email", fatherEmail);
  infoRow("Mobile", fatherMobile);
  doc.moveDown();

  // ===== Mother Details =====
  sectionHeading("Mother Details");
  infoRow("Name", motherName);
  infoRow("Email", motherEmail);
  infoRow("Mobile", motherMobile);
  doc.moveDown();

  // ===== Address =====
  sectionHeading("Address");
  infoRow("Door No", address.doorNo);
  infoRow("Street", address.street);
  infoRow("Taluk", address.taluk);
  infoRow("District", address.district);
  infoRow("State", address.state);
  infoRow("Pincode", address.pincode);
  doc.moveDown();

  // ===== Community & Course =====
  sectionHeading("Community & Course Details");
  infoRow("Community", community);
  infoRow("Courses Applied", courseRequired.length ? courseRequired.join(", ") : "-");
  doc.moveDown();

  // ===== Academic Details =====
  sectionHeading("Academic Details");
  infoRow("10th Board", tenthSchoolBoard);
  infoRow("12th School Name", twelfthSchoolName);
  infoRow("12th School Address", twelfthSchoolAddress);
  infoRow("12th Board", twelfthSchoolBoard);
  infoRow("12th Register No", twelfthRegisterNo);
  doc.moveDown(0.5);

  doc.fillColor("#2c3e50").fontSize(14).text("12th Marks", { underline: true });
  doc.moveDown(0.3);
  infoRow("Maths", twelfthMarks.maths);
  infoRow("Physics", twelfthMarks.physics);
  infoRow("Chemistry", twelfthMarks.chemistry);
  infoRow("Vocational (if any)", twelfthMarks.vocationalIfAny);
  infoRow("Total", twelfthMarks.total);
  infoRow("Cut Off", twelfthMarks.cutOff);
  doc.moveDown();

  // ===== Visit Info =====
  sectionHeading("Visit Information");
  infoRow("Date of Visit", dateOfVisit ? new Date(dateOfVisit).toLocaleDateString() : "-");

  doc.moveDown();

  // ===== Signature =====
  sectionHeading("Signature");
  if (signature && fs.existsSync(signature)) {
    doc.image(signature, { width: 150 });
  } else {
    infoRow("Signature", signature ? "Attached as base64 / file" : "Not Provided");
  }

  doc.moveDown(2);

  // ===== Footer =====
  doc.fontSize(10).fillColor("gray").text("Generated by SECE Admission Portal", { align: "center" });
};
